# Generated by Django 4.1.4 on 2023-01-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=1000000000)),
                ('expense_description', models.CharField(max_length=60)),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=1000000000)),
            ],
        ),
    ]
